version: '3.1'
services:
  payara:
    build: ../images/payara
    environment:
     - ADMIN_PASSWORD=adminadmin
    ports:
     - "8080:8080"
     - "4848:4848"
  db:
    image: mysql:5
    volumes: 
      - ../volumeMySQL:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=50M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: amt_project_1_pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
